
// Objective-C API for talking to the following Go packages
//
//	labs/simple
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Simple_FRAMEWORK_H__
#define __Simple_FRAMEWORK_H__

#include "Simple.objc.h"
#include "Universe.objc.h"

#endif
