// Objective-C API for talking to labs/simple Go package.
//   gobind -lang=objc labs/simple
//
// File is generated by gobind. Do not edit.

#ifndef __Simple_H__
#define __Simple_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class SimpleCtxt;
@class SimpleKeyPairs;
@class SimpleKeyPairsPublic;
@class SimpleKeyPairsSecret;

@interface SimpleCtxt : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field Ctxt.Data with unsupported type: github.com/tuneinsight/lattigo/v4/rlwe.Ciphertext

@end

@interface SimpleKeyPairs : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field KeyPairs.Public with unsupported type: labs/simple.KeyPairsPublic

// skipped field KeyPairs.Secret with unsupported type: labs/simple.KeyPairsSecret

@end

@interface SimpleKeyPairsPublic : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field KeyPairsPublic.Params with unsupported type: github.com/tuneinsight/lattigo/v4/ckks.Parameters

// skipped field KeyPairsPublic.Pk with unsupported type: github.com/tuneinsight/lattigo/v4/rlwe.PublicKey

@end

@interface SimpleKeyPairsSecret : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field KeyPairsSecret.Params with unsupported type: github.com/tuneinsight/lattigo/v4/ckks.Parameters

// skipped field KeyPairsSecret.Sk with unsupported type: github.com/tuneinsight/lattigo/v4/rlwe.SecretKey

@end

FOUNDATION_EXPORT NSString* _Nonnull SimpleDecodeDecrypt(NSString* _Nullable ctxt_base64_str, NSString* _Nullable key_pairs_secret_base64_str);

// skipped function Decode_ctxt with unsupported parameter or return types


// skipped function Decode_key_pairs with unsupported parameter or return types


// skipped function Decode_key_pairs_public with unsupported parameter or return types


// skipped function Decode_key_pairs_secret with unsupported parameter or return types


// skipped function Decrypt with unsupported parameter or return types


// skipped function Encode_ctxt with unsupported parameter or return types


// skipped function Encode_key_pairs with unsupported parameter or return types


// skipped function Encode_key_pairs_public with unsupported parameter or return types


// skipped function Encode_key_pairs_secret with unsupported parameter or return types


// skipped function Encrypt with unsupported parameter or return types


FOUNDATION_EXPORT NSString* _Nonnull SimpleEncryptEncode(NSString* _Nullable key_pairs_public_base64_str);

FOUNDATION_EXPORT NSString* _Nonnull SimpleKeyGen(void);

FOUNDATION_EXPORT NSString* _Nonnull SimpleKeyPairs_to_public_encode(NSString* _Nullable key_pairs_base64_str);

FOUNDATION_EXPORT NSString* _Nonnull SimpleKeyPairs_to_secret_encode(NSString* _Nullable key_pairs_base64_str);

FOUNDATION_EXPORT int32_t SimpleMultiply(int32_t value);

#endif
